Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -18,7 +18,8 @@ deploy_to_server:
       ssh -v -i "$SSH_KEY" \
           -o StrictHostKeyChecking=no \
           -o IdentitiesOnly=yes \
-          ${SERVER_USER}@${SERVER_IP} "
+          ${SERVER_USER}@${SERVER_IP} 'bash -s' << 'ENDSSH'
+        set -e
         echo '--- Connected to server ---'
 
         if ! command -v docker &> /dev/null; then
@@ -34,6 +35,10 @@ deploy_to_server:
           sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
           sudo apt-get update
           sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
+          if ! getent group docker > /dev/null; then
+            echo "Docker group not found. Creating..."
+            sudo groupadd docker
+          fi
           sudo usermod -aG docker \${USER}
         else
           echo 'Docker is already installed.'
